name: Cypress Tests CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  cypress-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.15.0'
        cache: 'npm'

    - name: Install dependencies
      run: yarn

    - name: Start application
      run: yarn dev &
      env:
        CI: true

    - name: Run Cypress e2e tests
      run: yarn cypress:run:e2e
      env:
        CI: true

    - name: Run Cypress component tests
      run: yarn cypress:run:component
      env:
        CI: true
